CREATE TABLE IF NOT EXISTS "staging_character_flags" (
  "server_id" TEXT,
  "character_id" CHAR(32),
  "character_name" TEXT,
  "level" INT,
  "job_id" CHAR(32),
  "job_grow_id" CHAR(32),
  "job_name" TEXT,
  "job_grow_name" TEXT,
  "fame" INT,
  "adventure_name" TEXT,
  "guild_id" CHAR(32),
  "guild_name" TEXT,
  "item_id" CHAR(32),
  "item_name" TEXT,
  "item_rarity" TEXT,
  "reinforce" INT,
  "reinforce_status" TEXT,
  "gems_0_slot_no" INT,
  "gems_0_item_id" CHAR(32),
  "gems_0_item_name" TEXT,
  "gems_0_item_rarity" TEXT,
  "gems_1_slot_no" INT,
  "gems_1_item_id" CHAR(32),
  "gems_1_item_name" TEXT,
  "gems_1_item_rarity" TEXT,
  "gems_2_slot_no" INT,
  "gems_2_item_id" CHAR(32),
  "gems_2_item_name" TEXT,
  "gems_2_item_rarity" TEXT,
  "gems_3_slot_no" INT,
  "gems_3_item_id" CHAR(32),
  "gems_3_item_name" TEXT,
  "gems_3_item_rarity" TEXT,
  "fetched_at" TIMESTAMP WITH TIME ZONE
);