CREATE TABLE IF NOT EXISTS "staging_character_creatures" (
  "server_id" TEXT,
  "character_id" CHAR(32),
  "character_name" TEXT,
  "level" INT,
  "job_id" CHAR(32),
  "job_grow_id" CHAR(32),
  "job_name" TEXT,
  "job_grow_name" TEXT,
  "fame" INT,
  "adventure_name" TEXT,
  "guild_id" CHAR(32),
  "guild_name" TEXT,
  "item_id" CHAR(32),
  "item_name" TEXT,
  "item_rarity" TEXT,
  "clone_item_id" CHAR(32),
  "clone_item_name" TEXT,
  "artifact_red_item_id" CHAR(32),
  "artifact_red_item_name" TEXT,
  "artifact_red_item_available_level" INT,
  "artifact_red_item_rarity" TEXT,
  "artifact_blue_item_id" CHAR(32),
  "artifact_blue_item_name" TEXT,
  "artifact_blue_item_available_level" INT,
  "artifact_blue_item_rarity" TEXT,
  "artifact_green_item_id" CHAR(32),
  "artifact_green_item_name" TEXT,
  "artifact_green_item_available_level" INT,
  "artifact_green_item_rarity" TEXT,
  "fetched_at" TIMESTAMP WITH TIME ZONE
);