# 서버 ID 가 key NAME 이 value
SERVER_ID_TO_NAME = {
    'anton': '안톤',
    'bakal': '바칼',
    'cain': '카인',
    'casillas': '카시야스',
    'diregie': '디레지에',
    'hilder': '힐더',
    'prey': '프레이',
    'siroco': '시로코'
    }

SERVER_NAME_TO_ID = {v : k for k, v in SERVER_ID_TO_NAME.items()}

SERVER_ID_LIST = list(SERVER_ID_TO_NAME.keys())

CHARACTER_STATUS_TRANSLATION_MAP = {
    '모험단 버프' : 'adventure',
    '무제한 길드능력치' : 'permanent_guild_stats',
    '기간제 길드능력치' : 'temporary_guild_stats',
    'HP': 'hp',
    'MP': 'mp',
    '물리 방어율': 'physical_defense_rate',
    '마법 방어율': 'magical_defense_rate',
    '힘': 'strength',
    '지능': 'intelligence',
    '체력': 'vitality',
    '정신력': 'spirit',
    '물리 공격': 'physical_attack',
    '마법 공격': 'magical_attack',
    '물리 크리티컬': 'physical_critical_chance',
    '마법 크리티컬': 'magical_critical_chance',
    '독립 공격': 'independent_attack',
    '공격 속도': 'attack_speed',
    '캐스팅 속도': 'casting_speed',
    '이동 속도': 'movement_speed',
    '모험가 명성': 'fame',
    '적중률': 'hit_rate',
    '회피율': 'evasion_rate',
    'HP 회복량': 'hp_recovery',
    'MP 회복량': 'mp_recovery',
    '경직도': 'stiffness',
    '히트리커버리': 'hit_recovery',
    '화속성 강화': 'fire_element_enhancement',
    '화속성 저항': 'fire_element_resistance',
    '수속성 강화': 'water_element_enhancement',
    '수속성 저항': 'water_element_resistance',
    '명속성 강화': 'light_element_enhancement',
    '명속성 저항': 'light_element_resistance',
    '암속성 강화': 'dark_element_enhancement',
    '암속성 저항': 'dark_element_resistance',
    '물리 방어': 'physical_defense',
    '마법 방어': 'magical_defense',
    '공격력 증가': 'attack_power_increase',
    '버프력': 'buff_power',
    '공격력 증폭': 'attack_power_amplification',
    '버프력 증폭': 'buff_power_amplification',
    '최종 데미지 증가': 'final_damage_increase',
    '쿨타임 감소': 'cooldown_reduction',
    '쿨타임 회복속도': 'cooldown_recovery_rate',
    '최종 쿨타임 감소율': 'final_cooldown_reduction_rate',
    '데미지 증가': 'damage_increase',
    '크리티컬 데미지 증가': 'critical_damage_increase',
    '추가 데미지 증가': 'additional_damage_increase',
    '모든 공격력 증가': 'all_attack_power_increase',
    '물리 공격력 증가': 'physical_attack_power_increase',
    '마법 공격력 증가': 'magical_attack_power_increase',
    '독립 공격력 증가': 'independent_attack_power_increase',
    '힘 증가': 'strength_increase',
    '지능 증가': 'intelligence_increase',
    '지속피해': 'damage_over_time',
    '물리 피해 감소': 'physical_damage_reduction',
    '마법 피해 감소': 'magical_damage_reduction',
    '출혈 피해 전환': 'bleed_damage_conversion',
    '중독 피해 전환': 'poison_damage_conversion',
    '화상 피해 전환': 'burn_damage_conversion',
    '감전 피해 전환': 'electrocution_damage_conversion',
    '출혈 내성': 'bleed_resistance',
    '중독 내성': 'poison_resistance',
    '화상 내성': 'burn_resistance',
    '감전 내성': 'electrocution_resistance',
    '빙결 내성': 'freeze_resistance',
    '둔화 내성': 'slow_resistance',
    '기절 내성': 'stun_resistance',
    '저주 내성': 'curse_resistance',
    '암흑 내성': 'darkness_resistance',
    '석화 내성': 'petrification_resistance',
    '수면 내성': 'sleep_resistance',
    '혼란 내성': 'confusion_resistance',
    '구속 내성': 'restraint_resistance',
    '화속성 피해': 'fire_element_damage',
    '수속성 피해': 'water_element_damage',
    '명속성 피해': 'light_element_damage',
    '암속성 피해': 'dark_element_damage',
    '출혈 피해': 'bleed_damage',
    '중독 피해': 'poison_damage',
    '화상 피해': 'burn_damage',
    '감전 피해': 'electrocution_damage'
}