from dotenv import load_dotenv
import os

# .env로 환경변수 불러오기
load_dotenv()

class Settings:
    # API 키 설정
    API_KEYS = [key.strip() for key in os.getenv('PYNEOPLE_API_KEYS').split(',') if key.strip()]

    # MongoDB 설정
    MONGO_URL=os.getenv('PYNEOPLE_MONGO_URL')
    MONGO_DB_NAME=os.getenv('PYNEOPLE_MONGO_DB_NAME')
    MONGO_COLLECTION_NAME=os.getenv('PYNEOPLE_MONGO_COLLECTION_NAME')
    MONGO_ERROR_COLLECTION_NAME=os.getenv('PYNEOPLE_MONGO_ERROR_COLLECTION_NAME')

    # PostgreSQL 설정
    POSTGRES_HOST=os.getenv('PYNEOPLE_POSTGRES_HOST')
    POSTGRES_PORT=int(os.getenv('PYNEOPLE_POSTGRES_PORT'))
    POSTGRES_USER=os.getenv('PYNEOPLE_POSTGRES_USER')
    POSTGRES_PASSWORD=os.getenv('PYNEOPLE_POSTGRES_PASSWORD')
    POSTGRES_DB=os.getenv('PYNEOPLE_POSTGRES_DB')

    # 디폴트 값들
    DEFAULT_SEEDER_BATCH_SIZE = 1000
    DEFAULT_NUM_API_FETCH_WORKERS = 100
    DEFAULT_API_REQUEST_QUEUE_SIZE = 1000
    DEFAULT_DATA_QUEUE_SIZE = 1000
    DEFAULT_NUM_MONGO_STORE_WORKERS = 10
    DEFAULT_MONGO_STORE_BATCH_SIZE = 2000
    DEFAULT_NUM_MONGO_ROUTERS = 8
    DEFAULT_MONGO_ROUTER_BATCH_SIZE = 3000
    DEFAULT_MONGO_TO_PSQL_QUEUE_SIZE = 1000
    DEFAULT_NUM_QUEUE_TO_PSQL_WORKERS = 4
    DEFAULT_QUEUE_TO_PSQL_BATCH_SIZE = 2000
    DEFAULT_TIMEOUT = 1
    DEFAULT_QUEUE_TO_PSQL_WORKER_TIMEOUT = 0.01
    DEFAULT_MAX_RETRIES = 3
    
    request_count = 0